### ISSUE TITLE
Why index document with sentence, not chunks 🤔

### ISSUE THREAD

**Issue by othsueh** [NTNU-SE-Alpha/AI_backend#3]
https://github.com/NTNU-SE-Alpha/AI_backend/blob/c163d707d7926eef67ee167595af4ae4258a8ee1/AI_teacher.py#L88-L103

Based on code above, my acknowledge is that this use sentence for index, not chunks. So I wonder why you use one sentence one index rather than one chunk one index, is there any reason or advantage for that?

BTW if you are thinking about chunk splitter, here is the one [LangChain](https://python.langchain.com/docs/how_to/recursive_text_splitter/#splitting-text-from-languages-without-word-boundaries)

**Comment by david2003-bite-10-23** [comment]
chunks  跟 sentence 比起來，sentence在匹配靈活性上更加高效，他能夠使回答的精準度更高

**Comment by othsueh** [comment]
sentence 跟 chunk 比確實靈活性比較高也比較簡短，但我不確定他能不能讓回答精準度更高。
因為 chunk 跟 sentence 比的話會含有更多上下文訊息，方便 LLM 去做更貼近文件內容的方式回答。目前你們測的文件 sentence 比 chunk 表現好，但假設如果有其他文件需要更多的上下文訊息讓 LLM 理解，那你們會怎麼解決?

**Comment by david2003-bite-10-23** [comment]
我認為這是取捨的問題，使用sentence可以更加精準的定位到訊息，但卻會忽略上下文的部分，但如果使用chunk，雖說會拿到更多的上下文的部分，但也會有更多的風險拿到無關的訊息，這樣會使對話變得較為不精準。 這部分如果需要的話也許下一次可以開會討論。
